name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix git safe directory
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global --add safe.directory /__w/skyland-beta/skyland-beta

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget tar bzip2 python3 python3-pip cmake
          pip3 install --break-system-packages pillow
          
      - name: Build project
        run: |
          cd build
          cmake -DGBA_AUTOBUILD_IMG=ON -DGBA_AUTOBUILD_CONF=ON -DCMAKE_TOOLCHAIN_FILE=$(pwd)/devkitarm.cmake .
          make -j && ./bundle.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyland-gba
          path: build/Skyland.gba
          
      - name: Test rom with mgba
        run: |
          sudo snap install mgba
          cd build
          mgba Skyland.gba

